### ISSUE TITLE
Limit available energy models in puzzle maker

### ISSUE THREAD

**Issue by luxaritas** [eternagame/EternaJS#139]
Eg, LinearFold shouldn't be available when creating a switch.

**Comment by AlexHalb** [comment]
Apart from LinearFold, what other restrictions on available models are there?

**Comment by luxaritas** [comment]
It actually isn't tied to the model itself - there's methods on the models that return whether or not a model supports a particular feature, eg in this case canFoldWithBindingSite.

**Comment by AlexHalb** [comment]
I realized I can create a `Puzzle` to represent the puzzlemaker state and use its `canUseFolder`.
