### ISSUE TITLE
Show custom labels for, e.g., helices

### ISSUE THREAD

**Issue by rhiju** [eternagame/EternaJS#198]
Its hard to consult with each other or with the literature about ribosomes based on numbering alone. Helix labels ('H88', 'h43', etc.) could provide a quick win in this regard.  Would also be straightforward to label certain important loops (e.g., decoding site, A-loop & P-loop).

Proposal here is to use a similar (or the same) labeling scheme used for numbers to also show helix labels (which @rhiju has worked out for all the ribosome helices in ribodraw). 

It may also be possible to show more extended sub-domains, though less obvious how to automatically place those labels -- those can perhaps be discussed in a separate thread. 

@omei please add any further thoughts/wishes you might have or that have come in from the community.

**Comment by luxaritas** [comment]
Annotations handle this
