### ISSUE TITLE
The folding engine selector appears above constraint descriptions

### ISSUE THREAD

**Issue by guyguy2001** [eternagame/EternaJS#204]
![image](https://user-images.githubusercontent.com/6932278/70943119-c4409880-2058-11ea-82bb-0f1a8e2d9664.png)

**Comment by BurtHarris** [comment]
Some repro steps would help me tackle this.    A puzzle number for example.

**Comment by luxaritas** [comment]
Puzzle 8747977 can repro this. Make sure multiple folding engines is on in the settings, and then hover over the constraint box

**Comment by BurtHarris** [comment]
How can I figure out what layer (Container?) the TextBalloon triggered by the hover is installed into?

**Comment by luxaritas** [comment]
It should be in the constraint box

**Comment by AlexHalb** [comment]
This can be closed.

**Comment by luxaritas** [comment]
@AlexHalb This is still an issue with the dropdown:
![image](https://user-images.githubusercontent.com/18635705/89462497-7b4e6900-d73b-11ea-9d2f-dec287147a84.png)

**Comment by AlexHalb** [comment]
I just saw that and was about to comment. I'll look in to it
