### ISSUE TITLE
Folding engine displayed in challenge puzzles

### ISSUE THREAD

**Issue by Omei** [eternagame/EternaJS#207]
It would be helpful if a challenge puzzle displayed the folding engine it was using. This could look exactly like it does in lab puzzles, with the only distinction being that it couldn't be changed by the player.

As it is, players (especially new ones) can easily be confused because a special boost they thought they understood doesn't work, for no observable reason.

**Comment by BurtHarris** [comment]
Where should this go in the code?

**Comment by luxaritas** [comment]
The folder button is created in PoseEditMode. 

Currently there’s a setting to enable/disable multiple folding engines, which affects this from showing even on puzzles where you can change it. I’m not sure how we should handle it. Should we change the setting description to just show/hide in both cases? Should we change it to only be used to hide when there’s no option for multiple folders? Do we need both? I don’t have a good grasp on what players would want

**Comment by luxaritas** [comment]
We have many more engines now, and more puzzles in other engines. I have been well convinced that we should always show the current engine, but just not allow it to be changed on challenge puzzles.
