### ISSUE TITLE
Replace src/eterna/util/Utility generateParameterString with URLSearchParams

### ISSUE THREAD

**Issue by luxaritas** [eternagame/EternaJS#211]
The utility function `generateParameterString` can be handled using the built-in`URLSearchParams`, ie via `var params = new URLSearchParams({"foo" : 1 , "bar" : 2});`

We should remove the `generateParameterString` function, and everywhere it's used, use `URLSearchParams` instead

**Comment by tolumide-ng** [comment]
@luxaritas
