### ISSUE TITLE
Promise.resolve() inside async functions is redundant

### ISSUE THREAD

**Issue by BurtHarris** [eternagame/EternaJS#219]
Using `return Promise.resolve()` inside a function declared as `async`  isn't really wrong, but unnecessary.   The code might be more readable if these were eliminated.

It looks like there are about 20 instances of this throughout the code base.

**Comment by BurtHarris** [comment]
@luxaritas How's your experience of using async/await so far.   Do you think it might be worthwhile to convert other places where `Promise.resolve()` get's called into async functions?

**Comment by luxaritas** [comment]
Yes - anywhere we can use `async` functions and `await` over manually creating/returning/resolving/rejecting promises, we should. There are a few instances where we're wrapping async code handled through events and not promises, but most situations are just holdover from when Tim initially did it.

**Comment by BurtHarris** [comment]
Interesting case in the EternaApp [setup function](https://github.com/eternagame/EternaJS/blob/7d3bc02ad9df6835af9cf9670ddb45fbcaffd42d/src/eterna/EternaApp.ts#L150), which is not itself `async`, but it looks like it occurs under an async lambda (another construct I've never thought about.)

**Comment by BurtHarris** [comment]
This was way less significant than I though...
