### ISSUE TITLE
Recent regression in new pseudoknot puzzles

### ISSUE THREAD

**Issue by Omei** [eternagame/EternaJS#259]
AWatkin's recent additions to support pseudoknots (both layout and energy modeling) seem to have been broken by some other recent change. For example:
![Andy's pseudoknot](https://user-images.githubusercontent.com/5702744/78708592-3c142680-78c7-11ea-9f2f-c0b868f7878c.png)
In target mode, the main puzzle should have the same as the thubnail. This is not the only puzzle that is showing oddities.

**Comment by luxaritas** [comment]
There haven't been any relevant changes. @everyday847 thoughts?

**Comment by luxaritas** [comment]
Seems fixed
