### ISSUE TITLE
ShowUIHighlight command fix

### ISSUE THREAD

**Issue by aminere** [eternagame/EternaJS#273]
`ShowUIHighlight` displays a misplaced rectangle on certain elements, I think it's not taking the transform hierarchy into account.
Needed by [Nova Tutorial 1.1](https://www.pbs.org/wgbh/nova/labs/lab/rna/research#/nceg/1/1) for highlighting the nucleotide palette.

**Comment by luxaritas** [comment]
Resolved in #274
