### ISSUE TITLE
Areas where target structure not meant are difficult to see on large puzzles

### ISSUE THREAD

**Issue by AlexHalb** [eternagame/EternaJS#302]
I've noticed this happening a lot on puzzles with more than 500 bases or so, especially very tall or wide designs. The target structure constraint will have a red outline, but it is impossible to see where the issue is. This means I have to look through and see where it is misfolding in natural mode. For very small misfolds, this takes a lot of time. I suggest we display a larger version of the target structure when the constraint box is hovered over, or at least display problematic bases and pairs.

**Comment by luxaritas** [comment]
If you click the constraint box, it will add red highlights on the RNA itself - does that resolve this concern?

**Comment by AlexHalb** [comment]
Yes, thanks. I didn't realize clicking did that.
