### ISSUE TITLE
Design info sidebar in feedback view

### ISSUE THREAD

**Issue by luxaritas** [eternagame/EternaJS#374]
With the new design browser design, we need to add the ability for the sidebar to show in FeedbackViewMode like we did with PoseEditMode, including the info button in the top right to open the panel if it isnt already

**Comment by everyday847** [comment]
Right now the info button comes along with the full HelpBar, all of which we wouldn't want to implement in FeedbackViewMode. We could decompose it, I suppose, but that's a minor pain. We would put it there instead of the 'go to home' link, I hope.

**Comment by everyday847** [comment]
OK, I've done this.
