### ISSUE TITLE
Make new design browser as compact as the original

### ISSUE THREAD

**Issue by luxaritas** [eternagame/EternaJS#375]
I had already pulled down the margins between rows, but per Eli's feedback we need to do this further due to ease of comparing sequences. Per Sharif, would be nice to keep them at least a little larger than the legacy browser to improve readability though

**Comment by luxaritas** [comment]
Per further discussion, we're compacting this down to how it was originally. We'll probably want to make this an option in the future, per, #409

**Comment by everyday847** [comment]
done woo
