### ISSUE TITLE
Sequence sort button in pose edit/feedback view should redirect to design browser AND apply sort

### ISSUE THREAD

**Issue by luxaritas** [eternagame/EternaJS#380]

**Comment by everyday847** [comment]
It's not quite clear how to do that actually, at least not to me. How do you queue up behaviors that DBM should apply at the start? I suppose an obvious gross way is to pass a nuisance flag upon construction, but that seems like a bit of logic that shouldn't bleed over.

IMO if you're in PEM/FVM, that button (or perhaps a button with a new icon just for the purpose) should JUST take you back to DBM -- I think that's actively better. I'd be surprised if I reordered content in a window I'm not even looking at right now!
