### ISSUE TITLE
Button on design sidebar to return to browser in pose edit and feedback view

### ISSUE THREAD

**Issue by luxaritas** [eternagame/EternaJS#381]
Since this was a point of confusion for a couple players. Sharif is looking at options here

**Comment by everyday847** [comment]
IMO this overlaps severely with #380 but that's personal ideology. I think we could replace the ~ icon in PEM/FVM and then we're done. We're half-there as is.

**Comment by everyday847** [comment]
OK, 90% of what we need is the icon here. Rest is trivial. @luxaritas what's the icon status from @sharife ?
