### ISSUE TITLE
Design browser thumbnail buttons are offcenter

### ISSUE THREAD

**Issue by luxaritas** [eternagame/EternaJS#389]
Both the copy/view and see result thumbnail buttons show the thumbnails offcenter (and I think overflowing the buttons too)

**Comment by everyday847** [comment]
A `ThumbnailAndTextButton` has a 52x52 rounded rectangle. `playThumbnail`, for example, is constructed via

```
PoseThumbnail.drawToSprite(
            playThumbnail,
            EPars.stringToSequence(this._props.solution.sequence),
            EPars.parenthesisToPairs(this._props.puzzle.getSecstruct()),
            3, PoseThumbnailType.BASE_COLORED,
            0, null, false, 0, customLayout
        );
```

where, you're gonna love this, the size is 3. 

3 means: 

```
frame = DisplayUtil.fillRect(62, 62, 0x0);
```

so OK, that's the trouble. I'm gonna make the thumbnails ten pixels bigger.

**Comment by everyday847** [comment]
That was a terrible idea! Because there are many `ThumbnailAndTextButton`s that don't rely on that thumbnail size, but that thumbnail size is always used for such buttons. So I shrank it, and now it's less bad.
