### ISSUE TITLE
Dropdown for folding engines

### ISSUE THREAD

**Issue by luxaritas** [eternagame/EternaJS#403]
Especially now that we have many engines, it would be great if we could have a dropdown so that you don't have to toggle through to get to the one you want - especially on long puzzles where evaluation can take a while

**Comment by AlexHalb** [comment]
I can work on this

**Comment by luxaritas** [comment]
@AlexHalb FYI, I did start to implement a dropdown in the puzzlemaker-constraints branch (see #158) - the UI might need to be made more generic to work for this case though

**Comment by AlexHalb** [comment]
Fantastic. I was hoping I wouldn't have to write up a class.
