### ISSUE TITLE
Shape thumbnail rendering artifact

### ISSUE THREAD

**Issue by luxaritas** [eternagame/EternaJS#405]
Via Ahalb. See the red line going off to the left. (sample pid: 9888587)
![image](https://user-images.githubusercontent.com/18635705/88747467-d15c5480-d11c-11ea-95b2-217d32b8e74e.png)

**Comment by everyday847** [comment]
That's truly an artifact of a broken customLayout -- note that it's the h2-defined 16S. The 16S customLayout was not designed to have h2 defined so it's broken.
