### ISSUE TITLE
Base pair numbers are offcenter

### ISSUE THREAD

**Issue by luxaritas** [eternagame/EternaJS#407]
Via Ahalb
![image](https://user-images.githubusercontent.com/18635705/88747943-d968c400-d11d-11ea-8723-f3ef19c3c648.png)

**Comment by everyday847** [comment]
Exact positioning in NucleotidePalette is arduous and depends on the text.width field in what seems to be a not quite linear way, which is pretty agonizing. Or at least, it's maybe also dependent on some third factor....
