### ISSUE TITLE
View Nucleotide Range is completely borked in the current build.

### ISSUE THREAD

**Issue by Omei** [eternagame/EternaJS#411]
Executing it results in a variety of results, from doing nothing, to moving to the wrong section, to this:
![View Nucleotide Range](https://user-images.githubusercontent.com/5702744/88870753-058e4e80-d1cb-11ea-9bff-1658dac19204.png)

**Comment by luxaritas** [comment]
For clarity - this is a bug in 1.8.5 not 1.9

**Comment by everyday847** [comment]
@Omei did you ask it to view 1-2? I guess it just doesn't turn the base rope off?

**Comment by Omei** [comment]
@everyday847 I was confusing this command with shifting the focus, e.g Jumo to Nucleotide. Let me go back and see if that accounts for everything that seemed wrong.
