### ISSUE TITLE
Move to next design in sidebar after deletion

### ISSUE THREAD

**Issue by luxaritas** [eternagame/EternaJS#413]
Doesn't make sense to continue showing a deleted design, especially since it no longer exists! Probably the procedure is reloading the design at the current index, and wrapping around to the beginning if there aren't any others

**Comment by luxaritas** [comment]
We should probably also immediately refresh the list before hiding the "deleting" message, as otherwise it looks like the design hasnt been deleted

**Comment by everyday847** [comment]
We call getSolutionsForPuzzles **then** cleanup, and it's the latter that destroys the status text. So that is OK. I think I've implemented the desired behavior, but you might have to demo it -- I don't have anything I can pretend to delete.
