### ISSUE TITLE
The view designs does not work in the lab browse page

### ISSUE THREAD

**Issue by everyday847** [eternagame/EternaJS#514]
Reported by jnicol

**Comment by everyday847** [comment]
I cannot reproduce on eternadev. I load up https://eternadev.org/labs/10169380 and click "solutions" on a puzzle and it's fine.

I suspect that this is a roundabout way of reporting #512 actually -- contrary to my expectation. Can we mark as redundant?

**Comment by luxaritas** [comment]
Considering this redundant
