### ISSUE TITLE
EA metric in Ribosome partials is broken

### ISSUE THREAD

**Issue by Omei** [eternagame/EternaJS#523]
In the R3 partial puzzles, e.g. https://eternagame.org/game/browse/10178083/,  I am seeing the EA constraint showing a value that is stuck at 0.000. And yet I see submissions, e.g. https://eternagame.orghttps://eternagame.org/game/browse/10178083/?filter1=Id&filter1_arg1=10309346&filter1_arg2=10309346 that imply the constraint was working at some point in the past.

**Comment by everyday847** [comment]
This was fixed, I think in ee6556f -- it certainly works on live.
