### ISSUE TITLE
Some files aren't minified

### ISSUE THREAD

**Issue by ch1ck3n-byte** [eternagame/EternaJS#525]
Eh, I'm playing eterna after a long time, and it's loading very slow. I believe minifying some of the js files would help improve the speed.
Here are some of the files that aren't minified:

https://eternagame.org/workbranch_main/frontend/jscripts/usermanager.js
https://eternagame.org/workbranch_main/frontend/jscripts/json/json2.js
https://eternagame.org/workbranch_main/frontend/jscripts/jquery/jquery-unselectable.js
https://eternagame.org/workbranch_main/frontend/jscripts/jquery-form/jquery.form.js
https://eternagame.org/workbranch_main/frontend/jscripts/table/jquery.dataTables.js
https://eternagame.org/workbranch_main/frontend/jscripts/table/jquery.dataTables.columnFilter.js
https://eternagame.org/workbranch_main/frontend/jscripts/fireworks/fireworks.js

here is the full list:

https://pastebin.com/g1rGRpwe

I also believe this CSS file can be minified:

https://eternagame.org/workbranch_main/frontend/themes/css/eterna.css

**Comment by luxaritas** [comment]
This is a leftover from our old website. It'll be resolved once we migrate over to a new EternaScript runtime, which has been started here: https://github.com/eternagame/eternagame.org/pull/200

**Comment by ch1ck3n-byte** [comment]
If it's a leftover, why can't we delete those files from the player?

**Comment by luxaritas** [comment]
They're still needed to run Eternascripts
