### ISSUE TITLE
When browsing through designs, the right panel and puzzle being displayed are getting out of sync.

### ISSUE THREAD

**Issue by Omei** [eternagame/EternaJS#544]
There is a very serious bug in viewing individual designs in the design browser where the design being displayed gets out of sync with the right panel.
![Serious browsing bug](https://user-images.githubusercontent.com/5702744/120876600-872ad780-c566-11eb-9397-2b6e11c15c87.png)
When this happens, there is no hint that the two are out of sync and so you are drawing incorrect conclusions about the designs.

In order to make sure that this was not being caused by one of the boosters, I went to an old  SHAPE lab and reproduced it there. 

The easiest way to reproduce seems to be to select a design from the table, click on Next followed immediately by Previous. The right panel will get updated but the main screen won't.

**Comment by luxaritas** [comment]
Apparently there were a handful of bugs in design swapping. I took care of the ones I could find in #547.
