### ISSUE TITLE
Annotations aren't compatible with custom numbering

### ISSUE THREAD

**Issue by Omei** [eternagame/EternaJS#583]
The initial implementation of annotations isn't aware of custom numbering, which limits which puzzles they can be used with. For example, in the Ribosome challenge series, an annotation created for the 23 subunit can cause a crash in a copy/paste operation to a 23S subpuzzle because the annotation code doesn't know how to to translate between raw position indices and custom numbering.

**Comment by luxaritas** [comment]
Pretty sure we've since resolved this, if not please re-open
