### ISSUE TITLE
MS2 Stamper tool sometimes flickers upon cursor hover

### ISSUE THREAD

**Issue by sbutkovi** [eternagame/EternaJS#592]
The MS2 Stamper tool (which features prominently in the Supercomputer questline) seems to have an issue where it sometimes flickers when you hover the cursor over it. This is not just a visual bug - it also affects the player's ability to select the tool (sometimes clicking on it repeatedly works, and sometimes it's more reliable to select something else on the toolbar before trying to click on it again).

It is also worth noting that the tool does not always flicker, even upon hovering - sometimes it behaves just like all of the other tools. I have not yet discovered a consistent "trigger" for this behavior.

Here are some screenshots illustrating this issue for both Dev and Prod. These screenshots did not capture the cursor, but all of them were taken while the cursor was hovering over the MS2 Stamper tool. All of these screenshots were taken in incognito mode on Chrome on a Mac; I've also confirmed that similar behavior exists for non-incognito mode on Chrome on a Mac.
![Screen Shot 2021-11-27 at 12 45 41 AM](https://user-images.githubusercontent.com/35237235/143671478-10658195-d3e2-4de2-866c-26e9d9de6ed8.png)
![Screen Shot 2021-11-27 at 12 46 26 AM](https://user-images.githubusercontent.com/35237235/143671480-f42234ae-749b-46ca-b865-1bc734df3f80.png)
![Screen Shot 2021-11-27 at 12 47 18 AM](https://user-images.githubusercontent.com/35237235/143671481-79a70bb6-334c-4275-85be-08e8039c798e.png)
![Screen Shot 2021-11-27 at 12 47 48 AM](https://user-images.githubusercontent.com/35237235/143671482-79926e4f-f240-4354-ab98-4537a2553ddf.png)

**Comment by luxaritas** [comment]
I'm going to assume this has since been resolved with the new toolbar we implemented some time back. If not, feel free to reopen.
