### ISSUE TITLE
In-puzzle text labels sometimes get stuck on screen

### ISSUE THREAD

**Issue by sbutkovi** [eternagame/EternaJS#613]
Within puzzles, I've noticed several instances where text labels appear on screen and it's not entirely sure how to get rid of them and/or what they correspond to. It's possible that this issue is related to EternaJS and not to this repository - however, I have been unable thus far to replicate the issue on the website version of the game on a desktop.

![text_labels_1](https://user-images.githubusercontent.com/35237235/158740150-956c6bf6-1c6b-4332-97fa-4e62ac8ed385.png)
![text_labels_2](https://user-images.githubusercontent.com/35237235/158740153-db11c2fc-9dd5-454b-849c-508c632b7afa.png)
![text_labels_3](https://user-images.githubusercontent.com/35237235/158740190-3a9d901f-12f1-4cb0-bcf2-2a4c6035e7c3.png)

**Comment by luxaritas** [comment]
I believe this has been resolved among various pointer interaction updates I've made - if not, please re-open
