### ISSUE TITLE
Toolbar falls off edge of screen, but no scrolling arrows to navigate it.

### ISSUE THREAD

**Issue by sbutkovi** [eternagame/EternaJS#614]
"Toolbar/settings currently fall off the edge - but pretty sure this isn't a new issue and should be fixed with the new toolbar, fingers crossed"

"It's supposed to have scrolling arrows if it doesn't fit…"

Tested on 1.4.1 on iPhone 8.

![pic1](https://user-images.githubusercontent.com/35237235/155815853-0493d752-8643-44f2-85f3-bfe52730b084.PNG)

**Comment by luxaritas** [comment]
Resolved in 26591a9ce61d8aa8f0c724b3ae59d73d01a2968b
