### ISSUE TITLE
Eterna3D on mobile app - "maximize" actually decreases Eterna3D window size

### ISSUE THREAD

**Issue by sbutkovi** [eternagame/EternaJS#625]
Screenshots attached. It's just a slightly confusing name for the observed behavior of that button. I'm guessing the size of the starting window is hard-coded in somewhere, thus the discrepancy?

Upon loading puzzle:

![pic1](https://user-images.githubusercontent.com/35237235/160920065-0941382f-6736-41e8-82f5-2b5ae4279497.PNG)

Upon clicking "maximize":

![pic2](https://user-images.githubusercontent.com/35237235/160920078-d5dabd1f-70e6-40da-b60a-416a7dbacecd.png)

**Comment by luxaritas** [comment]
First to note is that this isn't actually mobile specific. What's going on here is that our "maximized mode" has a minimal padding on each side of the window to prevent it from overlapping the toolbar, etc. I'm surprised that what you're showing is the starting window size - it shouldn't start off the screen like that. While in general the issue of "maximizing" shrinking the window in some cases is probably a wontfix (though it is admittedly confusing), it's probably worth investigating the initial window size (and its relation to the max size)
