### ISSUE TITLE
Sorting in design browser does not appear to work

### ISSUE THREAD

**Issue by sbutkovi** [eternagame/EternaJS#637]
Sorting in the design browser does not appear to work on mobile or on a desktop, at least not within a reasonable timeframe (screenshots from an attempted sort on mobile below).

![pic1](https://user-images.githubusercontent.com/35237235/162647538-bddad824-c04e-4a76-a967-616f91441184.PNG)

![pic2](https://user-images.githubusercontent.com/35237235/162647544-cdec793e-4f6b-41a9-bf8d-fc251002af9e.png)

(Aside - I was also testing the Configure functionality, which does appear to work - so ignore the non-default column ordering within the screenshots.)

**Comment by luxaritas** [comment]
Looks to be working
