### ISSUE TITLE
Eterna3D visual bug - missing backbone between 2 consecutive bases

### ISSUE THREAD

**Issue by sbutkovi** [eternagame/EternaJS#656]
Example pictured below: the 2 bases I have set as G (positions 4 and 5) should be connected with a backbone, but the backbone is missing. To the best of my knowledge, I believe this is an issue with EternaJS and not with the original .pdb file.

![pic1](https://user-images.githubusercontent.com/35237235/176987967-49ba53fd-26f8-48ce-bcbc-ae2b1285e43a.PNG)

This bug was observed both in puzzle maker (before publishing the puzzle) and in the final puzzle.

Here is the page for the puzzle I am encountering this issue on: https://eternagame.org/puzzles/11340342

**Comment by sbutkovi** [comment]
For the record, it appears there indeed instead may have been an issue with the original .pdb file, as an analogous visual oddity was observed within PyMOL.

**Comment by luxaritas** [comment]
Going to assume this was a PDB issue
