### ISSUE TITLE
White energy number greater than zero

### ISSUE THREAD

**Issue by luxaritas** [eternagame/EternaJS#69]
Via MasterStormer
https://noflash.eternagame.org/game/puzzle/6502964/
![image](https://user-images.githubusercontent.com/18635705/46760270-9cf57b00-cc9f-11e8-9f9c-b72551a804bf.png)

**Comment by BurtHarris** [comment]
Repro case from #185 is https://eternagame.org/game/puzzle/6502963/.   Seems to depend on state of solution, reset puzzle to initial state and reload, and node number '5' shows in red.

**Comment by BurtHarris** [comment]
Root cause may be in BitmapManager.getTextBitmapImpl(),  where bitmaps are cached without regard to the color (or bold etc) of the requested text.
