### ISSUE TITLE
Better layout for small screens

### ISSUE THREAD

**Issue by luxaritas** [eternagame/EternaJS#89]
E.g., collapsing tools into flyout menus

**Comment by luxaritas** [comment]
This has been improved somewhat, though there is still more work needed to support instances past the tutorials (and likely on smaller screens)

**Comment by rhiju** [comment]
the load blurbs often goes off screens -- not the best thing for players to see as their first intro to eterna!

**Comment by luxaritas** [comment]
Going to create specific issues
